benefits:
  - title: Reliability
    description: Improve uptime & reliability of your network
  - title: Efficiency
    description: Reduce costs by boosting efficiency & streamlining operations
  - title: Focus
    description: Free up time to be able to focus on your priorities

use_cases:
  - title: Faster issue resolution
    description: We naturally guide operators towards the problem across data sources and layers, enabling real-time root cause analysis.
    image: bolt.jpg
  - title: Actionable alerts & reports
    description: We make alerts actionable by adding the missing context to correlate, aggregate and filter them before they reach your inbox.
    image: alert.jpg
  - title: What-if & resilience analysis
    description: We improve availability and proactively prevent incidents by leveraging our models to evaluate what-if scenarios.
    image: shield.jpg
  - title: Meaningful AIOps
    description: We unlock large language models (LLMs) for network data, and combine them with our mathematical models where their reasoning abilities fall short.
    image: AI.jpg

product_features:
  - image: connected-globe.jpg
    description: NetFabric connects ALL data sources and infers missing pieces to create a comprehensive view of your network.
  - image: lightbulb.jpg
    description: NetFabric provides real-time answers and actionable insights to any network-related question.

quotes:
  - person: Senior network engineer managing a large university network
    quote: We have invested person-years into these problems!
  - person: CTO at a network monitoring company
    quote: Connecting data together is the holy grail!
  - person: Senior network engineer with over 10 years of hands-on experience
    quote: Support for multiple vendors is key for us!
